import type {
  AttendanceLog,
  AttendanceListParams,
  AttendanceStatus,
} from "@/types/attendance";

// ════════════════════════════════════════════
// ATTENDANCE LOG DUMMY DATA
// ════════════════════════════════════════════

// Helper untuk generate tanggal 30 hari terakhir
const getDateString = (daysAgo: number): string => {
  const date = new Date("2026-04-07"); // Current date sesuai context
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString().split("T")[0];
};

const getTimestamp = (dateStr: string, time: string): string => {
  return `${dateStr}T${time}:00Z`;
};

export const DUMMY_ATTENDANCE_LOGS: AttendanceLog[] = [
  // Hari ini - present
  {
    id: 1,
    employee_id: 1,
    employee_name: "Ahmad Fauzan",
    employee_number: "EMP-001",
    schedule_id: 1,
    attendance_date: getDateString(0),
    clock_in_at: getTimestamp(getDateString(0), "07:55"),
    clock_out_at: null,
    clock_in_lat: -7.2575,
    clock_in_lng: 112.7521,
    clock_out_lat: null,
    clock_out_lng: null,
    clock_in_photo_url: "https://placehold.co/400x300/d4537e/white?text=Clock+In",
    clock_out_photo_url: null,
    clock_in_method: "gps",
    clock_out_method: null,
    status: "present",
    permission_request_id: null,
    leave_request_id: null,
    business_trip_request_id: null,
    is_counted_as_full_day: false,
    late_minutes: 0,
    early_leave_minutes: 0,
    late_notes: null,
    early_leave_notes: null,
    late_document_url: null,
    overtime_minutes: 0,
    is_auto_generated: false,
    created_at: getTimestamp(getDateString(0), "07:55"),
    updated_at: getTimestamp(getDateString(0), "07:55"),
    deleted_at: null,
  },
  // Kemarin - late
  {
    id: 2,
    employee_id: 2,
    employee_name: "Fatimah Azzahra",
    employee_number: "EMP-002",
    schedule_id: 2,
    attendance_date: getDateString(1),
    clock_in_at: getTimestamp(getDateString(1), "08:25"),
    clock_out_at: getTimestamp(getDateString(1), "17:00"),
    clock_in_lat: -7.2575,
    clock_in_lng: 112.7521,
    clock_out_lat: -7.2575,
    clock_out_lng: 112.7521,
    clock_in_photo_url: "https://placehold.co/400x300/1d9e75/white?text=Clock+In",
    clock_out_photo_url: "https://placehold.co/400x300/185fa5/white?text=Clock+Out",
    clock_in_method: "gps",
    clock_out_method: "gps",
    status: "late",
    permission_request_id: null,
    leave_request_id: null,
    business_trip_request_id: null,
    is_counted_as_full_day: true,
    late_minutes: 25,
    early_leave_minutes: 0,
    late_notes: "Macet di jalan",
    early_leave_notes: null,
    late_document_url: null,
    overtime_minutes: 0,
    is_auto_generated: false,
    created_at: getTimestamp(getDateString(1), "08:25"),
    updated_at: getTimestamp(getDateString(1), "17:00"),
    deleted_at: null,
  },
  // 2 hari lalu - present
  {
    id: 3,
    employee_id: 3,
    employee_name: "Usman Hakim",
    employee_number: "EMP-003",
    schedule_id: 3,
    attendance_date: getDateString(2),
    clock_in_at: getTimestamp(getDateString(2), "07:50"),
    clock_out_at: getTimestamp(getDateString(2), "17:05"),
    clock_in_lat: -6.2088,
    clock_in_lng: 106.8456,
    clock_out_lat: -6.2088,
    clock_out_lng: 106.8456,
    clock_in_photo_url: null,
    clock_out_photo_url: null,
    clock_in_method: "manual",
    clock_out_method: "manual",
    status: "present",
    permission_request_id: null,
    leave_request_id: null,
    business_trip_request_id: null,
    is_counted_as_full_day: true,
    late_minutes: 0,
    early_leave_minutes: 0,
    late_notes: null,
    early_leave_notes: null,
    late_document_url: null,
    overtime_minutes: 5,
    is_auto_generated: false,
    created_at: getTimestamp(getDateString(2), "07:50"),
    updated_at: getTimestamp(getDateString(2), "17:05"),
    deleted_at: null,
  },
  // 3 hari lalu - present
  {
    id: 4,
    employee_id: 4,
    employee_name: "Aisyah Rahmawati",
    employee_number: "EMP-004",
    schedule_id: 4,
    attendance_date: getDateString(3),
    clock_in_at: getTimestamp(getDateString(3), "07:58"),
    clock_out_at: getTimestamp(getDateString(3), "17:02"),
    clock_in_lat: -7.2575,
    clock_in_lng: 112.7521,
    clock_out_lat: -7.2575,
    clock_out_lng: 112.7521,
    clock_in_photo_url: null,
    clock_out_photo_url: null,
    clock_in_method: "gps",
    clock_out_method: "gps",
    status: "present",
    permission_request_id: null,
    leave_request_id: null,
    business_trip_request_id: null,
    is_counted_as_full_day: true,
    late_minutes: 0,
    early_leave_minutes: 0,
    late_notes: null,
    early_leave_notes: null,
    late_document_url: null,
    overtime_minutes: 0,
    is_auto_generated: false,
    created_at: getTimestamp(getDateString(3), "07:58"),
    updated_at: getTimestamp(getDateString(3), "17:02"),
    deleted_at: null,
  },
  // 4 hari lalu - late
  {
    id: 5,
    employee_id: 5,
    employee_name: "Muhammad Rizki",
    employee_number: "EMP-005",
    schedule_id: 5,
    attendance_date: getDateString(4),
    clock_in_at: getTimestamp(getDateString(4), "08:35"),
    clock_out_at: getTimestamp(getDateString(4), "17:10"),
    clock_in_lat: -7.9783,
    clock_in_lng: 112.6321,
    clock_out_lat: -7.9783,
    clock_out_lng: 112.6321,
    clock_in_photo_url: null,
    clock_out_photo_url: null,
    clock_in_method: "gps",
    clock_out_method: "gps",
    status: "late",
    permission_request_id: null,
    leave_request_id: null,
    business_trip_request_id: null,
    is_counted_as_full_day: true,
    late_minutes: 35,
    early_leave_minutes: 0,
    late_notes: "Ban bocor di jalan",
    early_leave_notes: null,
    late_document_url: null,
    overtime_minutes: 0,
    is_auto_generated: false,
    created_at: getTimestamp(getDateString(4), "08:35"),
    updated_at: getTimestamp(getDateString(4), "17:10"),
    deleted_at: null,
  },
  // 5 hari lalu - present
  {
    id: 6,
    employee_id: 1,
    employee_name: "Ahmad Fauzan",
    employee_number: "EMP-001",
    schedule_id: 1,
    attendance_date: getDateString(5),
    clock_in_at: getTimestamp(getDateString(5), "07:45"),
    clock_out_at: getTimestamp(getDateString(5), "17:30"),
    clock_in_lat: -7.2575,
    clock_in_lng: 112.7521,
    clock_out_lat: -7.2575,
    clock_out_lng: 112.7521,
    clock_in_photo_url: null,
    clock_out_photo_url: null,
    clock_in_method: "gps",
    clock_out_method: "gps",
    status: "present",
    permission_request_id: null,
    leave_request_id: null,
    business_trip_request_id: null,
    is_counted_as_full_day: true,
    late_minutes: 0,
    early_leave_minutes: 0,
    late_notes: null,
    early_leave_notes: null,
    late_document_url: null,
    overtime_minutes: 30,
    is_auto_generated: false,
    created_at: getTimestamp(getDateString(5), "07:45"),
    updated_at: getTimestamp(getDateString(5), "17:30"),
    deleted_at: null,
  },
  // 6 hari lalu - half_day
  {
    id: 7,
    employee_id: 2,
    employee_name: "Fatimah Azzahra",
    employee_number: "EMP-002",
    schedule_id: 2,
    attendance_date: getDateString(6),
    clock_in_at: getTimestamp(getDateString(6), "08:00"),
    clock_out_at: getTimestamp(getDateString(6), "12:00"),
    clock_in_lat: -7.2575,
    clock_in_lng: 112.7521,
    clock_out_lat: -7.2575,
    clock_out_lng: 112.7521,
    clock_in_photo_url: null,
    clock_out_photo_url: null,
    clock_in_method: "gps",
    clock_out_method: "gps",
    status: "half_day",
    permission_request_id: 1,
    leave_request_id: null,
    business_trip_request_id: null,
    is_counted_as_full_day: false,
    late_minutes: 0,
    early_leave_minutes: 300,
    late_notes: null,
    early_leave_notes: "Urusan keluarga",
    late_document_url: null,
    overtime_minutes: 0,
    is_auto_generated: false,
    created_at: getTimestamp(getDateString(6), "08:00"),
    updated_at: getTimestamp(getDateString(6), "12:00"),
    deleted_at: null,
  },
  // 7 hari lalu - present
  {
    id: 8,
    employee_id: 3,
    employee_name: "Usman Hakim",
    employee_number: "EMP-003",
    schedule_id: 3,
    attendance_date: getDateString(7),
    clock_in_at: getTimestamp(getDateString(7), "07:55"),
    clock_out_at: getTimestamp(getDateString(7), "17:00"),
    clock_in_lat: -6.2088,
    clock_in_lng: 106.8456,
    clock_out_lat: -6.2088,
    clock_out_lng: 106.8456,
    clock_in_photo_url: null,
    clock_out_photo_url: null,
    clock_in_method: "gps",
    clock_out_method: "gps",
    status: "present",
    permission_request_id: null,
    leave_request_id: null,
    business_trip_request_id: null,
    is_counted_as_full_day: true,
    late_minutes: 0,
    early_leave_minutes: 0,
    late_notes: null,
    early_leave_notes: null,
    late_document_url: null,
    overtime_minutes: 0,
    is_auto_generated: false,
    created_at: getTimestamp(getDateString(7), "07:55"),
    updated_at: getTimestamp(getDateString(7), "17:00"),
    deleted_at: null,
  },
  // 8 hari lalu - leave (cuti)
  {
    id: 9,
    employee_id: 4,
    employee_name: "Aisyah Rahmawati",
    employee_number: "EMP-004",
    schedule_id: null,
    attendance_date: getDateString(8),
    clock_in_at: null,
    clock_out_at: null,
    clock_in_lat: null,
    clock_in_lng: null,
    clock_out_lat: null,
    clock_out_lng: null,
    clock_in_photo_url: null,
    clock_out_photo_url: null,
    clock_in_method: null,
    clock_out_method: null,
    status: "leave",
    permission_request_id: null,
    leave_request_id: 1,
    business_trip_request_id: null,
    is_counted_as_full_day: true,
    late_minutes: 0,
    early_leave_minutes: 0,
    late_notes: null,
    early_leave_notes: null,
    late_document_url: null,
    overtime_minutes: 0,
    is_auto_generated: true,
    created_at: getTimestamp(getDateString(8), "00:00"),
    updated_at: getTimestamp(getDateString(8), "00:00"),
    deleted_at: null,
  },
  // 9 hari lalu - leave (cuti)
  {
    id: 10,
    employee_id: 4,
    employee_name: "Aisyah Rahmawati",
    employee_number: "EMP-004",
    schedule_id: null,
    attendance_date: getDateString(9),
    clock_in_at: null,
    clock_out_at: null,
    clock_in_lat: null,
    clock_in_lng: null,
    clock_out_lat: null,
    clock_out_lng: null,
    clock_in_photo_url: null,
    clock_out_photo_url: null,
    clock_in_method: null,
    clock_out_method: null,
    status: "leave",
    permission_request_id: null,
    leave_request_id: 1,
    business_trip_request_id: null,
    is_counted_as_full_day: true,
    late_minutes: 0,
    early_leave_minutes: 0,
    late_notes: null,
    early_leave_notes: null,
    late_document_url: null,
    overtime_minutes: 0,
    is_auto_generated: true,
    created_at: getTimestamp(getDateString(9), "00:00"),
    updated_at: getTimestamp(getDateString(9), "00:00"),
    deleted_at: null,
  },
  // 10 hari lalu - present
  {
    id: 11,
    employee_id: 5,
    employee_name: "Muhammad Rizki",
    employee_number: "EMP-005",
    schedule_id: 5,
    attendance_date: getDateString(10),
    clock_in_at: getTimestamp(getDateString(10), "07:50"),
    clock_out_at: getTimestamp(getDateString(10), "17:00"),
    clock_in_lat: -7.9783,
    clock_in_lng: 112.6321,
    clock_out_lat: -7.9783,
    clock_out_lng: 112.6321,
    clock_in_photo_url: null,
    clock_out_photo_url: null,
    clock_in_method: "gps",
    clock_out_method: "gps",
    status: "present",
    permission_request_id: null,
    leave_request_id: null,
    business_trip_request_id: null,
    is_counted_as_full_day: true,
    late_minutes: 0,
    early_leave_minutes: 0,
    late_notes: null,
    early_leave_notes: null,
    late_document_url: null,
    overtime_minutes: 0,
    is_auto_generated: false,
    created_at: getTimestamp(getDateString(10), "07:50"),
    updated_at: getTimestamp(getDateString(10), "17:00"),
    deleted_at: null,
  },
  // 11 hari lalu - business_trip
  {
    id: 12,
    employee_id: 1,
    employee_name: "Ahmad Fauzan",
    employee_number: "EMP-001",
    schedule_id: null,
    attendance_date: getDateString(11),
    clock_in_at: null,
    clock_out_at: null,
    clock_in_lat: null,
    clock_in_lng: null,
    clock_out_lat: null,
    clock_out_lng: null,
    clock_in_photo_url: null,
    clock_out_photo_url: null,
    clock_in_method: null,
    clock_out_method: null,
    status: "business_trip",
    permission_request_id: null,
    leave_request_id: null,
    business_trip_request_id: 1,
    is_counted_as_full_day: true,
    late_minutes: 0,
    early_leave_minutes: 0,
    late_notes: null,
    early_leave_notes: null,
    late_document_url: null,
    overtime_minutes: 0,
    is_auto_generated: true,
    created_at: getTimestamp(getDateString(11), "00:00"),
    updated_at: getTimestamp(getDateString(11), "00:00"),
    deleted_at: null,
  },
  // 12 hari lalu - late
  {
    id: 13,
    employee_id: 2,
    employee_name: "Fatimah Azzahra",
    employee_number: "EMP-002",
    schedule_id: 2,
    attendance_date: getDateString(12),
    clock_in_at: getTimestamp(getDateString(12), "08:15"),
    clock_out_at: getTimestamp(getDateString(12), "17:00"),
    clock_in_lat: -7.2575,
    clock_in_lng: 112.7521,
    clock_out_lat: -7.2575,
    clock_out_lng: 112.7521,
    clock_in_photo_url: null,
    clock_out_photo_url: null,
    clock_in_method: "manual",
    clock_out_method: "manual",
    status: "late",
    permission_request_id: null,
    leave_request_id: null,
    business_trip_request_id: null,
    is_counted_as_full_day: true,
    late_minutes: 15,
    early_leave_minutes: 0,
    late_notes: "Hujan deras",
    early_leave_notes: null,
    late_document_url: null,
    overtime_minutes: 0,
    is_auto_generated: false,
    created_at: getTimestamp(getDateString(12), "08:15"),
    updated_at: getTimestamp(getDateString(12), "17:00"),
    deleted_at: null,
  },
  // 13 hari lalu - present
  {
    id: 14,
    employee_id: 3,
    employee_name: "Usman Hakim",
    employee_number: "EMP-003",
    schedule_id: 3,
    attendance_date: getDateString(13),
    clock_in_at: getTimestamp(getDateString(13), "07:48"),
    clock_out_at: getTimestamp(getDateString(13), "17:00"),
    clock_in_lat: -6.2088,
    clock_in_lng: 106.8456,
    clock_out_lat: -6.2088,
    clock_out_lng: 106.8456,
    clock_in_photo_url: null,
    clock_out_photo_url: null,
    clock_in_method: "gps",
    clock_out_method: "gps",
    status: "present",
    permission_request_id: null,
    leave_request_id: null,
    business_trip_request_id: null,
    is_counted_as_full_day: true,
    late_minutes: 0,
    early_leave_minutes: 0,
    late_notes: null,
    early_leave_notes: null,
    late_document_url: null,
    overtime_minutes: 0,
    is_auto_generated: false,
    created_at: getTimestamp(getDateString(13), "07:48"),
    updated_at: getTimestamp(getDateString(13), "17:00"),
    deleted_at: null,
  },
  // 14 hari lalu - absent (auto generated)
  {
    id: 15,
    employee_id: 5,
    employee_name: "Muhammad Rizki",
    employee_number: "EMP-005",
    schedule_id: null,
    attendance_date: getDateString(14),
    clock_in_at: null,
    clock_out_at: null,
    clock_in_lat: null,
    clock_in_lng: null,
    clock_out_lat: null,
    clock_out_lng: null,
    clock_in_photo_url: null,
    clock_out_photo_url: null,
    clock_in_method: null,
    clock_out_method: null,
    status: "absent",
    permission_request_id: null,
    leave_request_id: null,
    business_trip_request_id: null,
    is_counted_as_full_day: false,
    late_minutes: 0,
    early_leave_minutes: 0,
    late_notes: null,
    early_leave_notes: null,
    late_document_url: null,
    overtime_minutes: 0,
    is_auto_generated: true,
    created_at: getTimestamp(getDateString(14), "00:00"),
    updated_at: getTimestamp(getDateString(14), "00:00"),
    deleted_at: null,
  },
  // 15 hari lalu - present
  {
    id: 16,
    employee_id: 1,
    employee_name: "Ahmad Fauzan",
    employee_number: "EMP-001",
    schedule_id: 1,
    attendance_date: getDateString(15),
    clock_in_at: getTimestamp(getDateString(15), "07:52"),
    clock_out_at: getTimestamp(getDateString(15), "17:00"),
    clock_in_lat: -7.2575,
    clock_in_lng: 112.7521,
    clock_out_lat: -7.2575,
    clock_out_lng: 112.7521,
    clock_in_photo_url: null,
    clock_out_photo_url: null,
    clock_in_method: "gps",
    clock_out_method: "gps",
    status: "present",
    permission_request_id: null,
    leave_request_id: null,
    business_trip_request_id: null,
    is_counted_as_full_day: true,
    late_minutes: 0,
    early_leave_minutes: 0,
    late_notes: null,
    early_leave_notes: null,
    late_document_url: null,
    overtime_minutes: 0,
    is_auto_generated: false,
    created_at: getTimestamp(getDateString(15), "07:52"),
    updated_at: getTimestamp(getDateString(15), "17:00"),
    deleted_at: null,
  },
  // 16 hari lalu - present
  {
    id: 17,
    employee_id: 2,
    employee_name: "Fatimah Azzahra",
    employee_number: "EMP-002",
    schedule_id: 2,
    attendance_date: getDateString(16),
    clock_in_at: getTimestamp(getDateString(16), "07:58"),
    clock_out_at: getTimestamp(getDateString(16), "17:05"),
    clock_in_lat: -7.2575,
    clock_in_lng: 112.7521,
    clock_out_lat: -7.2575,
    clock_out_lng: 112.7521,
    clock_in_photo_url: null,
    clock_out_photo_url: null,
    clock_in_method: "gps",
    clock_out_method: "gps",
    status: "present",
    permission_request_id: null,
    leave_request_id: null,
    business_trip_request_id: null,
    is_counted_as_full_day: true,
    late_minutes: 0,
    early_leave_minutes: 0,
    late_notes: null,
    early_leave_notes: null,
    late_document_url: null,
    overtime_minutes: 0,
    is_auto_generated: false,
    created_at: getTimestamp(getDateString(16), "07:58"),
    updated_at: getTimestamp(getDateString(16), "17:05"),
    deleted_at: null,
  },
  // 17 hari lalu - holiday
  {
    id: 18,
    employee_id: 1,
    employee_name: "Ahmad Fauzan",
    employee_number: "EMP-001",
    schedule_id: null,
    attendance_date: getDateString(17),
    clock_in_at: null,
    clock_out_at: null,
    clock_in_lat: null,
    clock_in_lng: null,
    clock_out_lat: null,
    clock_out_lng: null,
    clock_in_photo_url: null,
    clock_out_photo_url: null,
    clock_in_method: null,
    clock_out_method: null,
    status: "holiday",
    permission_request_id: null,
    leave_request_id: null,
    business_trip_request_id: null,
    is_counted_as_full_day: true,
    late_minutes: 0,
    early_leave_minutes: 0,
    late_notes: null,
    early_leave_notes: null,
    late_document_url: null,
    overtime_minutes: 0,
    is_auto_generated: true,
    created_at: getTimestamp(getDateString(17), "00:00"),
    updated_at: getTimestamp(getDateString(17), "00:00"),
    deleted_at: null,
  },
  // 18 hari lalu - present with overtime
  {
    id: 19,
    employee_id: 3,
    employee_name: "Usman Hakim",
    employee_number: "EMP-003",
    schedule_id: 3,
    attendance_date: getDateString(18),
    clock_in_at: getTimestamp(getDateString(18), "07:50"),
    clock_out_at: getTimestamp(getDateString(18), "19:00"),
    clock_in_lat: -6.2088,
    clock_in_lng: 106.8456,
    clock_out_lat: -6.2088,
    clock_out_lng: 106.8456,
    clock_in_photo_url: null,
    clock_out_photo_url: null,
    clock_in_method: "gps",
    clock_out_method: "gps",
    status: "present",
    permission_request_id: null,
    leave_request_id: null,
    business_trip_request_id: null,
    is_counted_as_full_day: true,
    late_minutes: 0,
    early_leave_minutes: 0,
    late_notes: null,
    early_leave_notes: null,
    late_document_url: null,
    overtime_minutes: 120,
    is_auto_generated: false,
    created_at: getTimestamp(getDateString(18), "07:50"),
    updated_at: getTimestamp(getDateString(18), "19:00"),
    deleted_at: null,
  },
  // 19 hari lalu - late
  {
    id: 20,
    employee_id: 4,
    employee_name: "Aisyah Rahmawati",
    employee_number: "EMP-004",
    schedule_id: 4,
    attendance_date: getDateString(19),
    clock_in_at: getTimestamp(getDateString(19), "08:45"),
    clock_out_at: getTimestamp(getDateString(19), "17:00"),
    clock_in_lat: -7.2575,
    clock_in_lng: 112.7521,
    clock_out_lat: -7.2575,
    clock_out_lng: 112.7521,
    clock_in_photo_url: null,
    clock_out_photo_url: null,
    clock_in_method: "manual",
    clock_out_method: "manual",
    status: "late",
    permission_request_id: null,
    leave_request_id: null,
    business_trip_request_id: null,
    is_counted_as_full_day: true,
    late_minutes: 45,
    early_leave_minutes: 0,
    late_notes: "Kendaraan mogok",
    early_leave_notes: null,
    late_document_url: null,
    overtime_minutes: 0,
    is_auto_generated: false,
    created_at: getTimestamp(getDateString(19), "08:45"),
    updated_at: getTimestamp(getDateString(19), "17:00"),
    deleted_at: null,
  },
  // 20 hari lalu - present
  {
    id: 21,
    employee_id: 5,
    employee_name: "Muhammad Rizki",
    employee_number: "EMP-005",
    schedule_id: 5,
    attendance_date: getDateString(20),
    clock_in_at: getTimestamp(getDateString(20), "07:55"),
    clock_out_at: getTimestamp(getDateString(20), "17:00"),
    clock_in_lat: -7.9783,
    clock_in_lng: 112.6321,
    clock_out_lat: -7.9783,
    clock_out_lng: 112.6321,
    clock_in_photo_url: null,
    clock_out_photo_url: null,
    clock_in_method: "gps",
    clock_out_method: "gps",
    status: "present",
    permission_request_id: null,
    leave_request_id: null,
    business_trip_request_id: null,
    is_counted_as_full_day: true,
    late_minutes: 0,
    early_leave_minutes: 0,
    late_notes: null,
    early_leave_notes: null,
    late_document_url: null,
    overtime_minutes: 0,
    is_auto_generated: false,
    created_at: getTimestamp(getDateString(20), "07:55"),
    updated_at: getTimestamp(getDateString(20), "17:00"),
    deleted_at: null,
  },
  // 21 hari lalu - absent
  {
    id: 22,
    employee_id: 3,
    employee_name: "Usman Hakim",
    employee_number: "EMP-003",
    schedule_id: null,
    attendance_date: getDateString(21),
    clock_in_at: null,
    clock_out_at: null,
    clock_in_lat: null,
    clock_in_lng: null,
    clock_out_lat: null,
    clock_out_lng: null,
    clock_in_photo_url: null,
    clock_out_photo_url: null,
    clock_in_method: null,
    clock_out_method: null,
    status: "absent",
    permission_request_id: null,
    leave_request_id: null,
    business_trip_request_id: null,
    is_counted_as_full_day: false,
    late_minutes: 0,
    early_leave_minutes: 0,
    late_notes: null,
    early_leave_notes: null,
    late_document_url: null,
    overtime_minutes: 0,
    is_auto_generated: true,
    created_at: getTimestamp(getDateString(21), "00:00"),
    updated_at: getTimestamp(getDateString(21), "00:00"),
    deleted_at: null,
  },
  // 22 hari lalu - present
  {
    id: 23,
    employee_id: 1,
    employee_name: "Ahmad Fauzan",
    employee_number: "EMP-001",
    schedule_id: 1,
    attendance_date: getDateString(22),
    clock_in_at: getTimestamp(getDateString(22), "07:50"),
    clock_out_at: getTimestamp(getDateString(22), "17:00"),
    clock_in_lat: -7.2575,
    clock_in_lng: 112.7521,
    clock_out_lat: -7.2575,
    clock_out_lng: 112.7521,
    clock_in_photo_url: null,
    clock_out_photo_url: null,
    clock_in_method: "gps",
    clock_out_method: "gps",
    status: "present",
    permission_request_id: null,
    leave_request_id: null,
    business_trip_request_id: null,
    is_counted_as_full_day: true,
    late_minutes: 0,
    early_leave_minutes: 0,
    late_notes: null,
    early_leave_notes: null,
    late_document_url: null,
    overtime_minutes: 0,
    is_auto_generated: false,
    created_at: getTimestamp(getDateString(22), "07:50"),
    updated_at: getTimestamp(getDateString(22), "17:00"),
    deleted_at: null,
  },
  // 23 hari lalu - present
  {
    id: 24,
    employee_id: 2,
    employee_name: "Fatimah Azzahra",
    employee_number: "EMP-002",
    schedule_id: 2,
    attendance_date: getDateString(23),
    clock_in_at: getTimestamp(getDateString(23), "07:55"),
    clock_out_at: getTimestamp(getDateString(23), "17:00"),
    clock_in_lat: -7.2575,
    clock_in_lng: 112.7521,
    clock_out_lat: -7.2575,
    clock_out_lng: 112.7521,
    clock_in_photo_url: null,
    clock_out_photo_url: null,
    clock_in_method: "gps",
    clock_out_method: "gps",
    status: "present",
    permission_request_id: null,
    leave_request_id: null,
    business_trip_request_id: null,
    is_counted_as_full_day: true,
    late_minutes: 0,
    early_leave_minutes: 0,
    late_notes: null,
    early_leave_notes: null,
    late_document_url: null,
    overtime_minutes: 0,
    is_auto_generated: false,
    created_at: getTimestamp(getDateString(23), "07:55"),
    updated_at: getTimestamp(getDateString(23), "17:00"),
    deleted_at: null,
  },
  // 24 hari lalu - present
  {
    id: 25,
    employee_id: 4,
    employee_name: "Aisyah Rahmawati",
    employee_number: "EMP-004",
    schedule_id: 4,
    attendance_date: getDateString(24),
    clock_in_at: getTimestamp(getDateString(24), "07:58"),
    clock_out_at: getTimestamp(getDateString(24), "17:00"),
    clock_in_lat: -7.2575,
    clock_in_lng: 112.7521,
    clock_out_lat: -7.2575,
    clock_out_lng: 112.7521,
    clock_in_photo_url: null,
    clock_out_photo_url: null,
    clock_in_method: "gps",
    clock_out_method: "gps",
    status: "present",
    permission_request_id: null,
    leave_request_id: null,
    business_trip_request_id: null,
    is_counted_as_full_day: true,
    late_minutes: 0,
    early_leave_minutes: 0,
    late_notes: null,
    early_leave_notes: null,
    late_document_url: null,
    overtime_minutes: 0,
    is_auto_generated: false,
    created_at: getTimestamp(getDateString(24), "07:58"),
    updated_at: getTimestamp(getDateString(24), "17:00"),
    deleted_at: null,
  },
];

// ════════════════════════════════════════════
// GETTER FUNCTIONS
// ════════════════════════════════════════════

export function getDummyAttendanceLogs(
  params?: AttendanceListParams,
): AttendanceLog[] {
  let result = [...DUMMY_ATTENDANCE_LOGS];

  if (params?.employee_id) {
    result = result.filter((log) => log.employee_id === params.employee_id);
  }

  if (params?.status) {
    result = result.filter((log) => log.status === params.status);
  }

  if (params?.start_date) {
    result = result.filter((log) => log.attendance_date >= params.start_date!);
  }

  if (params?.end_date) {
    result = result.filter((log) => log.attendance_date <= params.end_date!);
  }

  // Sort by date descending (newest first)
  result.sort(
    (a, b) =>
      new Date(b.attendance_date).getTime() -
      new Date(a.attendance_date).getTime(),
  );

  return result;
}

export function getDummyAttendanceLogById(id: number): AttendanceLog | null {
  return DUMMY_ATTENDANCE_LOGS.find((log) => log.id === id) ?? null;
}

// Summary helper untuk dashboard
export function getDummyAttendanceSummary(params?: {
  start_date?: string;
  end_date?: string;
}): Record<AttendanceStatus, number> {
  const logs = getDummyAttendanceLogs(params);
  const summary: Record<AttendanceStatus, number> = {
    present: 0,
    late: 0,
    absent: 0,
    half_day: 0,
    leave: 0,
    business_trip: 0,
    holiday: 0,
  };

  logs.forEach((log) => {
    summary[log.status]++;
  });

  return summary;
}
